import tkinter
top=tkinter.Tk()
f1=tkinter.Frame(top)
f2=tkinter.Frame(top)
f1.pack(side=tkinter.TOP)
f2.pack(side=tkinter.BOTTOM)
b1=tkinter.Button(f1,text="button1",fg="red",bg="black",cursor="circle")
b2=tkinter.Button(f1,text="button2",fg="blue",bg="black",cursor="circle")
b3=tkinter.Button(f1,text="button3",fg="orange",bg="black",cursor="circle")
b4=tkinter.Button(f2,text="button4",fg="green",bg="black",cursor="circle")
b1.pack(side=tkinter.LEFT)
b2.pack(side=tkinter.LEFT)
b3.pack(side=tkinter.LEFT)
b4.pack(side=tkinter.LEFT)
